name: Sync Upstream Updates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Git credentials
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/docmost/docmost.git
        git fetch upstream

    - name: Rebase the fork with upstream/main
      run: |
        git rebase upstream/main

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: sync-upstream
        delete-branch: true
        title: 'Sync updates from upstream'
        body: |
          This pull request contains updates merged from the upstream repository.
          Please review the changes and merge them into the `main` branch if appropriate.